-- Migration: Add complete 20-product catalog across all collections with full galleries
-- Timestamp: 2026-10-01
-- Clean up placeholder and superseded records
DELETE FROM public.og_products
WHERE id IN (
  'og-voyager',
  'og-stats',
  'og-arcade',
  'og-comet',
  'og-discfest-towel',
  'og-pickleball',
  'everyday-is-pickle-day',
  'get-your-dink',
  'pickleball-lifestyle',
  'og-dink-different'
);

INSERT INTO public.og_products (
  id, slug, name, category, sports, collection_ids, base_price, price, image, gallery,
  colors, sizes, size_range, description, short_description, material, fabric_type,
  cut, variants, sold, stock, tag, tags, home_best_seller_rank, status
)
VALUES
  (
    'pilipinas-aouc-jersey',
    'pilipinas-aouc-jersey-2025',
    'PILIPINAS AOUC JERSEY 2025',
    'Pilipinas Collection',
    '{"Ultimate Frisbee"}'::text[],
    '{"pilipinas","discfest"}'::text[],
    1000,
    1000,
    '/images/products/pilipinas-aouc-capiz.webp',
    '{"/images/products/pilipinas-aouc-capiz.webp","/images/products/pilipinas-aouc-lilim.webp","/images/products/pilipinas-aouc-piloncitos.webp"}'::text[],
    '[{"name":"Capiz","value":"bg-[#E6DEC8]","variantSku":"OG-PILIPINAS-AOUC-SS-DRF-CAPIZ"},{"name":"Lilim","value":"bg-[#1E293B]","variantSku":"OG-PILIPINAS-AOUC-SS-DRF-LILIM"},{"name":"Piloncitos","value":"bg-[#D97706]","variantSku":"OG-PILIPINAS-AOUC-SS-DRF-PILONCITOS"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'Official Pilipinas AOUC 2025 National Team Jersey. Full sublimation dryfit activewear engineered for international ultimate tournament play.',
    'Pilipinas AOUC 2025 National Team Jersey · 2XS–5XL.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-PILIPINASAOUC-SS-DRF-CAPIZ","designName":"Capiz","isActive":true,"imageUrl":"/images/products/pilipinas-aouc-capiz.webp"},{"sku":"OG-PILIPINASAOUC-SS-DRF-LILIM","designName":"Lilim","isActive":true,"imageUrl":"/images/products/pilipinas-aouc-lilim.webp"},{"sku":"OG-PILIPINASAOUC-SS-DRF-PILONCITOS","designName":"Piloncitos","isActive":true,"imageUrl":"/images/products/pilipinas-aouc-piloncitos.webp"}]'::jsonb,
    145,
    null,
    'Best Seller',
    '{"Best Seller","Pilipinas","National Team"}'::text[],
    1,
    'active'
  ),
  (
    'pilipinas-ultimate-jersey',
    'pilipinas-ultimate-jersey',
    'PILIPINAS ULTIMATE TEAM JERSEY',
    'Pilipinas Collection',
    '{"Ultimate Frisbee"}'::text[],
    '{"pilipinas"}'::text[],
    1100,
    1100,
    '/images/products/pilipinas-ultimate-blue.webp',
    '{"/images/products/pilipinas-ultimate-blue.webp","/images/products/pilipinas-ultimate-white.webp"}'::text[],
    '[{"name":"National Blue","value":"bg-blue-700","variantSku":"OG-PILIPINAS-ULTIMATE-SS-DRF-NATIONALBLUE"},{"name":"National White","value":"bg-white","variantSku":"OG-PILIPINAS-ULTIMATE-SS-DRF-NATIONALWHITE"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'Pilipinas Ultimate Team Jersey featuring national heraldry and high-breathability performance mesh.',
    'Pilipinas Ultimate Jersey in Blue & White.',
    'Dryfit Polyester',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-PILIPINASULTIMATE-SS-DRF-NATIONALBLUE","designName":"National Blue","isActive":true,"imageUrl":"/images/products/pilipinas-ultimate-blue.webp"},{"sku":"OG-PILIPINASULTIMATE-SS-DRF-NATIONALWHITE","designName":"National White","isActive":true,"imageUrl":"/images/products/pilipinas-ultimate-white.webp"}]'::jsonb,
    88,
    null,
    'Pilipinas',
    '{"Pilipinas"}'::text[],
    0,
    'active'
  ),
  (
    'og-padayon-jersey',
    'og-padayon-jersey',
    'PADAYON PILIPINAS JERSEY',
    'Pilipinas Collection',
    '{"Ultimate Frisbee"}'::text[],
    '{"pilipinas"}'::text[],
    1200,
    1200,
    '/images/products/pilipinas-padayon-jersey.webp',
    '{"/images/products/pilipinas-padayon-jersey.webp","/images/community/community-pilipinas-portrait.jpg","/images/community/community-pilipinas-cap.jpg"}'::text[],
    '[{"name":"Pilipinas Gold & Sun","value":"bg-[#FFD700]","variantSku":"OG-PADAYON-TK-DRF-GOLDSUN"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL"}'::text[],
    '2XS–4XL',
    'Padayon Pilipinas sleeveless jersey with Baybayin script accents, Philippine Sun details, and customizable back player number.',
    'Padayon sleeveless national jersey with customizable number.',
    'Full Sublimation Dryfit (Customizable number)',
    'dri_fit',
    'tank',
    '[{"sku":"OG-PADAYON-TK-DRF-GOLDSUN","designName":"Gold Sun","isActive":true,"imageUrl":"/images/products/pilipinas-padayon-jersey.webp"}]'::jsonb,
    112,
    null,
    'Pilipinas',
    '{"Pilipinas"}'::text[],
    0,
    'active'
  ),
  (
    'running-line',
    'running-performance-line',
    'RUNNING PERFORMANCE LINE 2.0',
    'Running',
    '{"Running"}'::text[],
    '{"running"}'::text[],
    900,
    900,
    '/images/products/running-performance-cover.webp',
    '{"/images/products/running-performance-cover.webp","/images/products/running-classic-black.webp","/images/products/running-flow-state-blue.webp","/images/products/running-purpose-green.webp","/images/products/running-catch-me-cream.webp","/images/products/running-stride-club-gray.webp"}'::text[],
    '[{"name":"OFFGRID Classic (Black)","value":"bg-offgrid-dark","variantSku":"OG-RUNNING-LINE-SS-DRF-OFFGRIDCLASSICBLACK"},{"name":"The Flow State (Blue)","value":"bg-blue-600","variantSku":"OG-RUNNING-LINE-SS-DRF-THEFLOWSTATEBLUE"},{"name":"Run With Purpose (Green)","value":"bg-offgrid-green","variantSku":"OG-RUNNING-LINE-SS-DRF-RUNWITHPURPOSEGREEN"},{"name":"Catch Me If You Can (Cream)","value":"bg-offgrid-cream","variantSku":"OG-RUNNING-LINE-SS-DRF-CATCHMEIFYOUCANCREAM"},{"name":"The Stride Club (Dark Gray)","value":"bg-gray-700","variantSku":"OG-RUNNING-LINE-SS-DRF-THESTRIDECLUBDARKGRAY"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'Running Performance Line 2.0 — built for daily miles and tempo runs with featherweight moisture-wicking comfort.',
    'Running performance graphic tees.',
    'Running Mesh / Drifit',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-RUNNINGLINE-SS-DRF-OFFGRIDCLASSICBLACK","designName":"OFFGRID Classic Black","isActive":true,"imageUrl":"/images/products/running-classic-black.webp"},{"sku":"OG-RUNNINGLINE-SS-DRF-THEFLOWSTATEBLUE","designName":"The Flow State Blue","isActive":true,"imageUrl":"/images/products/running-flow-state-blue.webp"},{"sku":"OG-RUNNINGLINE-SS-DRF-RUNWITHPURPOSEGREEN","designName":"Run With Purpose Green","isActive":true,"imageUrl":"/images/products/running-purpose-green.webp"},{"sku":"OG-RUNNINGLINE-SS-DRF-CATCHMEIFYOUCANCREAM","designName":"Catch Me If You Can Cream","isActive":true,"imageUrl":"/images/products/running-catch-me-cream.webp"},{"sku":"OG-RUNNINGLINE-SS-DRF-THESTRIDECLUBDARKGRAY","designName":"The Stride Club Dark Gray","isActive":true,"imageUrl":"/images/products/running-stride-club-gray.webp"}]'::jsonb,
    320,
    null,
    'Top Rated',
    '{"Top Rated"}'::text[],
    2,
    'active'
  ),
  (
    'og-stride-running',
    'og-stride-collection',
    'OFF GRID STRIDE COLLECTION',
    'Running',
    '{"Running"}'::text[],
    '{"running"}'::text[],
    1000,
    1000,
    '/images/products/stride-running-banner.webp',
    '{"/images/products/stride-running-banner.webp","/images/products/stride-running-promo.webp","/images/products/stride-running-grid.webp","/images/products/stride-running-detail.webp"}'::text[],
    '[{"name":"White-Teal","value":"bg-teal-400","variantSku":"OG-STRIDE-SS-RUN-WHITETEAL"},{"name":"White-Pink","value":"bg-pink-400","variantSku":"OG-STRIDE-SS-RUN-WHITEPINK"},{"name":"White-Neon Green","value":"bg-lime-400","variantSku":"OG-STRIDE-SS-RUN-WHITENEONGREEN"},{"name":"White-Orange","value":"bg-orange-400","variantSku":"OG-STRIDE-SS-RUN-WHITEORANGE"},{"name":"Black-Teal","value":"bg-teal-700","variantSku":"OG-STRIDE-SS-RUN-BLACKTEAL"},{"name":"Black-Pink","value":"bg-pink-700","variantSku":"OG-STRIDE-SS-RUN-BLACKPINK"},{"name":"Black-Neon Green","value":"bg-lime-600","variantSku":"OG-STRIDE-SS-RUN-BLACKNEONGREEN"},{"name":"Pink-Teal","value":"bg-fuchsia-600","variantSku":"OG-STRIDE-SS-RUN-PINKTEAL"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'OFF GRID Stride Collection — high-visibility dual-tone colorways engineered for chasing PRs from morning intervals to night runs.',
    'Chasing PR dual-tone running shirts.',
    'Breathable Running Poly',
    'running_mesh',
    'short_sleeve',
    '[{"sku":"OG-STRIDE-SS-RUN-WHITETEAL","designName":"White-Teal","isActive":true,"imageUrl":"/images/products/stride-running-grid.webp"},{"sku":"OG-STRIDE-SS-RUN-WHITEPINK","designName":"White-Pink","isActive":true,"imageUrl":"/images/products/stride-running-grid.webp"},{"sku":"OG-STRIDE-SS-RUN-WHITENEONGREEN","designName":"White-Neon Green","isActive":true,"imageUrl":"/images/products/stride-running-grid.webp"},{"sku":"OG-STRIDE-SS-RUN-WHITEORANGE","designName":"White-Orange","isActive":true,"imageUrl":"/images/products/stride-running-grid.webp"},{"sku":"OG-STRIDE-SS-RUN-BLACKTEAL","designName":"Black-Teal","isActive":true,"imageUrl":"/images/products/stride-running-grid.webp"},{"sku":"OG-STRIDE-SS-RUN-BLACKPINK","designName":"Black-Pink","isActive":true,"imageUrl":"/images/products/stride-running-grid.webp"},{"sku":"OG-STRIDE-SS-RUN-BLACKNEONGREEN","designName":"Black-Neon Green","isActive":true,"imageUrl":"/images/products/stride-running-grid.webp"},{"sku":"OG-STRIDE-SS-RUN-PINKTEAL","designName":"Pink-Teal","isActive":true,"imageUrl":"/images/products/stride-running-grid.webp"}]'::jsonb,
    195,
    null,
    'Running',
    '{"Running"}'::text[],
    0,
    'active'
  ),
  (
    'og-motoline',
    'motoline',
    'OFF GRID LIFESTYLE — MOTOLINE',
    'Lifestyle / Motoline',
    '{"Lifestyle"}'::text[],
    '{"lifestyle","running"}'::text[],
    650,
    650,
    '/images/products/motoline-cover.webp',
    '{"/images/products/motoline-cover.webp","/images/products/motoline-full-throttle.webp","/images/products/motoline-takbong-og.webp","/images/products/motoline-stay-offgrid.webp","/images/products/motoline-takbong-pogi.webp"}'::text[],
    '[{"name":"FULL THROTTLE LIFE","value":"bg-offgrid-dark","variantSku":"OG-MOTOLINE-LS-DRF-FULLTHROTTLELIFE"},{"name":"TAKBONG OG","value":"bg-offgrid-green","variantSku":"OG-MOTOLINE-LS-DRF-TAKBONGOG"},{"name":"STAY OFFGRID","value":"bg-offgrid-lime","variantSku":"OG-MOTOLINE-LS-DRF-STAYOFFGRID"},{"name":"TAKBONG POGI MODE","value":"bg-offgrid-cream","variantSku":"OG-MOTOLINE-LS-DRF-TAKBONGPOGIMODE"}]'::jsonb,
    '{"XS","S","M","L","XL","2XL","3XL","4XL"}'::text[],
    'XS–4XL',
    'MOTOLINE long-sleeve lifestyle & moto kit — gritty street and road runs with iconic Filipino rider catchphrases in OFFGRID colorways.',
    'Long sleeve drifit lifestyle moto gear.',
    'Premium Drifit',
    'dri_fit',
    'long_sleeve',
    '[{"sku":"OG-MOTOLINE-LS-DRF-FULLTHROTTLELIFE","designName":"FULL THROTTLE LIFE","isActive":true,"imageUrl":"/images/products/motoline-full-throttle.webp"},{"sku":"OG-MOTOLINE-LS-DRF-TAKBONGOG","designName":"TAKBONG OG","isActive":true,"imageUrl":"/images/products/motoline-takbong-og.webp"},{"sku":"OG-MOTOLINE-LS-DRF-STAYOFFGRID","designName":"STAY OFFGRID","isActive":true,"imageUrl":"/images/products/motoline-stay-offgrid.webp"},{"sku":"OG-MOTOLINE-LS-DRF-TAKBONGPOGIMODE","designName":"TAKBONG POGI MODE","isActive":true,"imageUrl":"/images/products/motoline-takbong-pogi.webp"}]'::jsonb,
    154,
    null,
    'Trending',
    '{"Trending"}'::text[],
    4,
    'active'
  ),
  (
    'the-og-vibe-collection',
    'the-og-vibe-collection',
    'THE OG VIBE STREETWEAR TEE',
    'Lifestyle / OG Vibe',
    '{"Lifestyle"}'::text[],
    '{"lifestyle"}'::text[],
    850,
    850,
    '/images/products/og-vibe-photoshoot-banner.webp',
    '{"/images/products/og-vibe-photoshoot-banner.webp","/images/products/og-vibe-steampunk-black.webp","/images/products/og-vibe-blossom-black.webp","/images/products/og-vibe-steampunk-cream.webp","/images/products/og-vibe-blossom-cream.webp","/images/products/og-vibe-model-front.webp","/images/products/og-vibe-model-back.webp"}'::text[],
    '[{"name":"Black Steampunk","value":"bg-black","variantSku":"OG-THE-OG-VIBE-COLLECTION-SS-COT-BLACKSTEAMPUNK"},{"name":"Black Blossom","value":"bg-neutral-900","variantSku":"OG-THE-OG-VIBE-COLLECTION-SS-COT-BLACKBLOSSOM"},{"name":"Cream Steampunk","value":"bg-[#F5F2EB]","variantSku":"OG-THE-OG-VIBE-COLLECTION-SS-COT-CREAMSTEAMPUNK"},{"name":"Cream Blossom","value":"bg-offgrid-cream","variantSku":"OG-THE-OG-VIBE-COLLECTION-SS-COT-CREAMBLOSSOM"}]'::jsonb,
    '{"S","M","L","XL","2XL"}'::text[],
    'S–2XL',
    'Lifestyle streetwear for everyday athletes. Heavyweight cotton with premium screen-printed OG Steampunk and Blossom graphics.',
    'Heavyweight cotton streetwear tee.',
    'Heavyweight Cotton Streetwear',
    'cotton',
    'short_sleeve',
    '[{"sku":"OG-THEOGVIBECOLLECTION-SS-COT-BLACKSTEAMPUNK","designName":"Black Steampunk","isActive":true,"imageUrl":"/images/products/og-vibe-steampunk-black.webp"},{"sku":"OG-THEOGVIBECOLLECTION-SS-COT-BLACKBLOSSOM","designName":"Black Blossom","isActive":true,"imageUrl":"/images/products/og-vibe-blossom-black.webp"},{"sku":"OG-THEOGVIBECOLLECTION-SS-COT-CREAMSTEAMPUNK","designName":"Cream Steampunk","isActive":true,"imageUrl":"/images/products/og-vibe-steampunk-cream.webp"},{"sku":"OG-THEOGVIBECOLLECTION-SS-COT-CREAMBLOSSOM","designName":"Cream Blossom","isActive":true,"imageUrl":"/images/products/og-vibe-blossom-cream.webp"}]'::jsonb,
    430,
    null,
    'Lifestyle',
    '{"Lifestyle"}'::text[],
    0,
    'active'
  ),
  (
    'og-momentum-caps',
    'og-momentum-caps',
    'OFF GRID MOMENTUM ATHLETIC CAP',
    'Lifestyle',
    '{"Lifestyle"}'::text[],
    '{"lifestyle"}'::text[],
    950,
    950,
    '/images/products/momentum-cap-cover.webp',
    '{"/images/products/momentum-cap-cover.webp","/images/products/momentum-cap-dark-blue.webp","/images/products/momentum-cap-black.webp","/images/products/momentum-cap-white.webp","/images/products/momentum-cap-sky-blue.webp","/images/products/momentum-cap-pink.webp"}'::text[],
    '[{"name":"Dark Blue","value":"bg-blue-900","variantSku":"OG-MOMENTUM-CAPS-CP-PLY-DARKBLUE"},{"name":"Black","value":"bg-black","variantSku":"OG-MOMENTUM-CAPS-CP-PLY-BLACK"},{"name":"White","value":"bg-white","variantSku":"OG-MOMENTUM-CAPS-CP-PLY-WHITE"},{"name":"Sky Blue","value":"bg-sky-400","variantSku":"OG-MOMENTUM-CAPS-CP-PLY-SKYBLUE"},{"name":"Pink","value":"bg-pink-400","variantSku":"OG-MOMENTUM-CAPS-CP-PLY-PINK"}]'::jsonb,
    '{"One Size"}'::text[],
    'One Size (Adjustable strap)',
    'OFF GRID Lifestyle Momentum Caps — structured crown with moisture-managing sweatband and adjustable fit for sun protection and style.',
    'Breathable athletic cap with adjustable strap.',
    'Structured Breathable Twill',
    'poly_blend',
    'cap',
    '[{"sku":"OG-MOMENTUMCAPS-CP-PLY-DARKBLUE","designName":"Dark Blue","isActive":true,"imageUrl":"/images/products/momentum-cap-dark-blue.webp"},{"sku":"OG-MOMENTUMCAPS-CP-PLY-BLACK","designName":"Black","isActive":true,"imageUrl":"/images/products/momentum-cap-black.webp"},{"sku":"OG-MOMENTUMCAPS-CP-PLY-WHITE","designName":"White","isActive":true,"imageUrl":"/images/products/momentum-cap-white.webp"},{"sku":"OG-MOMENTUMCAPS-CP-PLY-SKYBLUE","designName":"Sky Blue","isActive":true,"imageUrl":"/images/products/momentum-cap-sky-blue.webp"},{"sku":"OG-MOMENTUMCAPS-CP-PLY-PINK","designName":"Pink","isActive":true,"imageUrl":"/images/products/momentum-cap-pink.webp"}]'::jsonb,
    70,
    null,
    'Headwear',
    '{"Headwear"}'::text[],
    0,
    'active'
  ),
  (
    'og-microfiber-towel',
    'og-microfiber-towel',
    'OFF GRID MICROFIBER PERFORMANCE TOWEL',
    'Lifestyle',
    '{"Lifestyle"}'::text[],
    '{"lifestyle"}'::text[],
    650,
    650,
    '/images/products/towel-microfiber-promo.webp',
    '{"/images/products/towel-microfiber-promo.webp","/images/products/towel-microfiber-progress.webp","/images/products/towel-microfiber-hand-spec.webp","/images/products/towel-microfiber-detail.webp","/images/products/towel-microfiber-flatlay.webp"}'::text[],
    '[{"name":"OFFGRID Lime / Field Black","value":"bg-offgrid-green","variantSku":"OG-MICROFIBER-TOWEL-AC-MCF-HAND35X75"}]'::jsonb,
    '{"Face (30x30)","Hand (35x75)","Bath (140x70)"}'::text[],
    'Face, Hand, Bath sizes',
    'Ultra-compact quick-drying microfiber performance towel. Dual-texture functionality: smooth high-definition printed face with high-absorption back loop.',
    'Quick-drying printed microfiber sports towel.',
    'Microfiber Blend (Polyester/Polyamide)',
    'poly_blend',
    'shorts',
    '[{"sku":"OG-MICROFIBERTOWEL-AC-MCF-FACE30X30","designName":"Face 30x30","isActive":true,"imageUrl":"/images/products/towel-microfiber-progress.webp"},{"sku":"OG-MICROFIBERTOWEL-AC-MCF-HAND35X75","designName":"Hand 35x75","isActive":true,"imageUrl":"/images/products/towel-microfiber-hand-spec.webp"},{"sku":"OG-MICROFIBERTOWEL-AC-MCF-BATH140X70","designName":"Bath 140x70","isActive":true,"imageUrl":"/images/products/towel-microfiber-flatlay.webp"}]'::jsonb,
    160,
    null,
    'Lifestyle',
    '{"Lifestyle"}'::text[],
    0,
    'active'
  ),
  (
    'og-primal-sleeveless',
    'og-primal-sleeveless',
    'OG PRIMAL POWER — SLEEVELESS TANK',
    'Primal Collection',
    '{"Gym & Training"}'::text[],
    '{"primal"}'::text[],
    900,
    900,
    '/images/products/primal-sleeveless-black-green.webp',
    '{"/images/products/primal-sleeveless-black-green.webp","/images/products/primal-sleeveless-blue-ivory.webp","/images/products/primal-sleeveless-green-pink.webp","/images/products/primal-sleeveless-teal-white.webp"}'::text[],
    '[{"name":"Black/Green","value":"bg-black","variantSku":"OG-PRIMAL-SLEEVELESS-SL-DRF-BLACKGREEN"},{"name":"Blue/Ivory","value":"bg-blue-800","variantSku":"OG-PRIMAL-SLEEVELESS-SL-DRF-BLUEIVORY"},{"name":"Green/Pink","value":"bg-emerald-700","variantSku":"OG-PRIMAL-SLEEVELESS-SL-DRF-GREENPINK"},{"name":"Teal/White","value":"bg-teal-600","variantSku":"OG-PRIMAL-SLEEVELESS-SL-DRF-TEALWHITE"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Primal Power Sleeveless Tank — maximum mobility for heavy lifts and intense conditioning sessions.',
    'Primal power sleeveless gym tank.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'sleeveless',
    '[{"sku":"OG-PRIMALSLEEVELESS-SL-DRF-BLACKGREEN","designName":"Black/Green","isActive":true,"imageUrl":"/images/products/primal-sleeveless-black-green.webp"},{"sku":"OG-PRIMALSLEEVELESS-SL-DRF-BLUEIVORY","designName":"Blue/Ivory","isActive":true,"imageUrl":"/images/products/primal-sleeveless-blue-ivory.webp"},{"sku":"OG-PRIMALSLEEVELESS-SL-DRF-GREENPINK","designName":"Green/Pink","isActive":true,"imageUrl":"/images/products/primal-sleeveless-green-pink.webp"},{"sku":"OG-PRIMALSLEEVELESS-SL-DRF-TEALWHITE","designName":"Teal/White","isActive":true,"imageUrl":"/images/products/primal-sleeveless-teal-white.webp"}]'::jsonb,
    180,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-primal-shortsleeve',
    'og-primal-shortsleeve',
    'OG PRIMAL POWER — SHORT SLEEVE',
    'Primal Collection',
    '{"Gym & Training"}'::text[],
    '{"primal"}'::text[],
    900,
    900,
    '/images/products/primal-shortsleeve-black-green.webp',
    '{"/images/products/primal-shortsleeve-black-green.webp","/images/products/primal-shortsleeve-blue-ivory.webp","/images/products/primal-shortsleeve-green-pink.webp","/images/products/primal-shortsleeve-teal-white.webp"}'::text[],
    '[{"name":"Black/Green","value":"bg-black","variantSku":"OG-PRIMAL-SHORTSLEEVE-SS-DRF-BLACKGREEN"},{"name":"Blue/Ivory","value":"bg-blue-800","variantSku":"OG-PRIMAL-SHORTSLEEVE-SS-DRF-BLUEIVORY"},{"name":"Green/Pink","value":"bg-emerald-700","variantSku":"OG-PRIMAL-SHORTSLEEVE-SS-DRF-GREENPINK"},{"name":"Teal/White","value":"bg-teal-600","variantSku":"OG-PRIMAL-SHORTSLEEVE-SS-DRF-TEALWHITE"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Primal Power Short Sleeve Tee — high-density sublimated gym gear tailored for training and physique.',
    'Primal power short sleeve performance shirt.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-PRIMALSHORTSLEEVE-SS-DRF-BLACKGREEN","designName":"Black/Green","isActive":true,"imageUrl":"/images/products/primal-shortsleeve-black-green.webp"},{"sku":"OG-PRIMALSHORTSLEEVE-SS-DRF-BLUEIVORY","designName":"Blue/Ivory","isActive":true,"imageUrl":"/images/products/primal-shortsleeve-blue-ivory.webp"},{"sku":"OG-PRIMALSHORTSLEEVE-SS-DRF-GREENPINK","designName":"Green/Pink","isActive":true,"imageUrl":"/images/products/primal-shortsleeve-green-pink.webp"},{"sku":"OG-PRIMALSHORTSLEEVE-SS-DRF-TEALWHITE","designName":"Teal/White","isActive":true,"imageUrl":"/images/products/primal-shortsleeve-teal-white.webp"}]'::jsonb,
    240,
    null,
    'Popular',
    '{"Popular"}'::text[],
    3,
    'active'
  ),
  (
    'og-primal-longsleeve',
    'og-primal-longsleeve',
    'OG PRIMAL POWER — LONG SLEEVE',
    'Primal Collection',
    '{"Gym & Training"}'::text[],
    '{"primal"}'::text[],
    1100,
    1100,
    '/images/products/primal-longsleeve-black-green.webp',
    '{"/images/products/primal-longsleeve-black-green.webp","/images/products/primal-longsleeve-blue-ivory.webp","/images/products/primal-longsleeve-green-pink.webp","/images/products/primal-longsleeve-teal-white.webp"}'::text[],
    '[{"name":"Black/Green","value":"bg-black","variantSku":"OG-PRIMAL-LONGSLEEVE-LS-DRF-BLACKGREEN"},{"name":"Blue/Ivory","value":"bg-blue-800","variantSku":"OG-PRIMAL-LONGSLEEVE-LS-DRF-BLUEIVORY"},{"name":"Green/Pink","value":"bg-emerald-700","variantSku":"OG-PRIMAL-LONGSLEEVE-LS-DRF-GREENPINK"},{"name":"Teal/White","value":"bg-teal-600","variantSku":"OG-PRIMAL-LONGSLEEVE-LS-DRF-TEALWHITE"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Primal Power Long Sleeve — athletic taper with full arm coverage for warmup, outdoors, and strength training.',
    'Primal power long sleeve performance shirt.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'long_sleeve',
    '[{"sku":"OG-PRIMALLONGSLEEVE-LS-DRF-BLACKGREEN","designName":"Black/Green","isActive":true,"imageUrl":"/images/products/primal-longsleeve-black-green.webp"},{"sku":"OG-PRIMALLONGSLEEVE-LS-DRF-BLUEIVORY","designName":"Blue/Ivory","isActive":true,"imageUrl":"/images/products/primal-longsleeve-blue-ivory.webp"},{"sku":"OG-PRIMALLONGSLEEVE-LS-DRF-GREENPINK","designName":"Green/Pink","isActive":true,"imageUrl":"/images/products/primal-longsleeve-green-pink.webp"},{"sku":"OG-PRIMALLONGSLEEVE-LS-DRF-TEALWHITE","designName":"Teal/White","isActive":true,"imageUrl":"/images/products/primal-longsleeve-teal-white.webp"}]'::jsonb,
    130,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-primal-hoodie',
    'og-primal-hoodie',
    'OG PRIMAL POWER — HOODIE',
    'Primal Collection',
    '{"Gym & Training"}'::text[],
    '{"primal"}'::text[],
    1100,
    1100,
    '/images/products/primal-hoodie-black-green.webp',
    '{"/images/products/primal-hoodie-black-green.webp","/images/products/primal-hoodie-blue-ivory.webp","/images/products/primal-hoodie-green-pink.webp","/images/products/primal-hoodie-teal-white.webp"}'::text[],
    '[{"name":"Black/Green","value":"bg-black","variantSku":"OG-PRIMAL-HOODIE-HD-DRF-BLACKGREEN"},{"name":"Blue/Ivory","value":"bg-blue-800","variantSku":"OG-PRIMAL-HOODIE-HD-DRF-BLUEIVORY"},{"name":"Green/Pink","value":"bg-emerald-700","variantSku":"OG-PRIMAL-HOODIE-HD-DRF-GREENPINK"},{"name":"Teal/White","value":"bg-teal-600","variantSku":"OG-PRIMAL-HOODIE-HD-DRF-TEALWHITE"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Primal Power Performance Hoodie — lightweight workout layer with drawstring hood and athletic cut.',
    'Primal power performance hoodie.',
    'Performance Sublimated Poly Hoodie',
    'dri_fit',
    'hoodie',
    '[{"sku":"OG-PRIMALHOODIE-HD-DRF-BLACKGREEN","designName":"Black/Green","isActive":true,"imageUrl":"/images/products/primal-hoodie-black-green.webp"},{"sku":"OG-PRIMALHOODIE-HD-DRF-BLUEIVORY","designName":"Blue/Ivory","isActive":true,"imageUrl":"/images/products/primal-hoodie-blue-ivory.webp"},{"sku":"OG-PRIMALHOODIE-HD-DRF-GREENPINK","designName":"Green/Pink","isActive":true,"imageUrl":"/images/products/primal-hoodie-green-pink.webp"},{"sku":"OG-PRIMALHOODIE-HD-DRF-TEALWHITE","designName":"Teal/White","isActive":true,"imageUrl":"/images/products/primal-hoodie-teal-white.webp"}]'::jsonb,
    95,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-solar-sleeveless',
    'og-solar-sleeveless',
    'OG SOLAR RISE — SLEEVELESS TANK',
    'Solar Collection',
    '{"Gym & Training"}'::text[],
    '{"solar"}'::text[],
    900,
    900,
    '/images/products/solar-sleeveless-white-teal.webp',
    '{"/images/products/solar-sleeveless-white-teal.webp","/images/products/solar-sleeveless-white-red.webp","/images/products/solar-sleeveless-blue-yellow.webp","/images/products/solar-sleeveless-black-teal.webp","/images/products/solar-sleeveless-black-yellow.webp"}'::text[],
    '[{"name":"White/Teal","value":"bg-teal-400","variantSku":"OG-SOLAR-SLEEVELESS-SL-DRF-WHITETEAL"},{"name":"White/Red","value":"bg-red-500","variantSku":"OG-SOLAR-SLEEVELESS-SL-DRF-WHITERED"},{"name":"Blue/Yellow","value":"bg-yellow-400","variantSku":"OG-SOLAR-SLEEVELESS-SL-DRF-BLUEYELLOW"},{"name":"Black/Teal","value":"bg-teal-700","variantSku":"OG-SOLAR-SLEEVELESS-SL-DRF-BLACKTEAL"},{"name":"Black/Yellow","value":"bg-neutral-900","variantSku":"OG-SOLAR-SLEEVELESS-SL-DRF-BLACKYELLOW"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Solar Rise Sleeveless Tank — energized graphics and lightweight ventilation for heavy training sessions.',
    'Solar Rise sleeveless athletic tank.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'sleeveless',
    '[{"sku":"OG-SOLARSLEEVELESS-SL-DRF-WHITETEAL","designName":"White/Teal","isActive":true,"imageUrl":"/images/products/solar-sleeveless-white-teal.webp"},{"sku":"OG-SOLARSLEEVELESS-SL-DRF-WHITERED","designName":"White/Red","isActive":true,"imageUrl":"/images/products/solar-sleeveless-white-red.webp"},{"sku":"OG-SOLARSLEEVELESS-SL-DRF-BLUEYELLOW","designName":"Blue/Yellow","isActive":true,"imageUrl":"/images/products/solar-sleeveless-blue-yellow.webp"},{"sku":"OG-SOLARSLEEVELESS-SL-DRF-BLACKTEAL","designName":"Black/Teal","isActive":true,"imageUrl":"/images/products/solar-sleeveless-black-teal.webp"},{"sku":"OG-SOLARSLEEVELESS-SL-DRF-BLACKYELLOW","designName":"Black/Yellow","isActive":true,"imageUrl":"/images/products/solar-sleeveless-black-yellow.webp"}]'::jsonb,
    110,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-solar-shortsleeve',
    'og-solar-shortsleeve',
    'OG SOLAR RISE — SHORT SLEEVE',
    'Solar Collection',
    '{"Gym & Training"}'::text[],
    '{"solar"}'::text[],
    1000,
    1000,
    '/images/products/solar-shortsleeve-white-teal.webp',
    '{"/images/products/solar-shortsleeve-white-teal.webp","/images/products/solar-shortsleeve-white-red.webp","/images/products/solar-shortsleeve-blue-yellow.webp"}'::text[],
    '[{"name":"White/Teal","value":"bg-teal-400","variantSku":"OG-SOLAR-SHORTSLEEVE-SS-DRF-WHITETEAL"},{"name":"White/Red","value":"bg-red-500","variantSku":"OG-SOLAR-SHORTSLEEVE-SS-DRF-WHITERED"},{"name":"Blue/Yellow","value":"bg-yellow-400","variantSku":"OG-SOLAR-SHORTSLEEVE-SS-DRF-BLUEYELLOW"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Solar Rise Short Sleeve — radiant gradient motifs on sweat-wicking dryfit fabric.',
    'Solar Rise short sleeve performance tee.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-SOLARSHORTSLEEVE-SS-DRF-WHITETEAL","designName":"White/Teal","isActive":true,"imageUrl":"/images/products/solar-shortsleeve-white-teal.webp"},{"sku":"OG-SOLARSHORTSLEEVE-SS-DRF-WHITERED","designName":"White/Red","isActive":true,"imageUrl":"/images/products/solar-shortsleeve-white-red.webp"},{"sku":"OG-SOLARSHORTSLEEVE-SS-DRF-BLUEYELLOW","designName":"Blue/Yellow","isActive":true,"imageUrl":"/images/products/solar-shortsleeve-blue-yellow.webp"}]'::jsonb,
    140,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-solar-longsleeve',
    'og-solar-longsleeve',
    'OG SOLAR RISE — LONG SLEEVE',
    'Solar Collection',
    '{"Gym & Training"}'::text[],
    '{"solar"}'::text[],
    1100,
    1100,
    '/images/products/solar-longsleeve-white-teal.webp',
    '{"/images/products/solar-longsleeve-white-teal.webp","/images/products/solar-longsleeve-white-red.webp","/images/products/solar-longsleeve-blue-yellow.webp"}'::text[],
    '[{"name":"White/Teal","value":"bg-teal-400","variantSku":"OG-SOLAR-LONGSLEEVE-LS-DRF-WHITETEAL"},{"name":"White/Red","value":"bg-red-500","variantSku":"OG-SOLAR-LONGSLEEVE-LS-DRF-WHITERED"},{"name":"Blue/Yellow","value":"bg-yellow-400","variantSku":"OG-SOLAR-LONGSLEEVE-LS-DRF-BLUEYELLOW"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Solar Rise Long Sleeve — solar flare graphics with full coverage against the sun and elements.',
    'Solar Rise long sleeve performance shirt.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'long_sleeve',
    '[{"sku":"OG-SOLARLONGSLEEVE-LS-DRF-WHITETEAL","designName":"White/Teal","isActive":true,"imageUrl":"/images/products/solar-longsleeve-white-teal.webp"},{"sku":"OG-SOLARLONGSLEEVE-LS-DRF-WHITERED","designName":"White/Red","isActive":true,"imageUrl":"/images/products/solar-longsleeve-white-red.webp"},{"sku":"OG-SOLARLONGSLEEVE-LS-DRF-BLUEYELLOW","designName":"Blue/Yellow","isActive":true,"imageUrl":"/images/products/solar-longsleeve-blue-yellow.webp"}]'::jsonb,
    90,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-golf',
    'og-links-golf-polo',
    'OFF GRID LIFESTYLE — LINKS GOLF POLO',
    'Golf',
    '{"Golf"}'::text[],
    '{"golf"}'::text[],
    1200,
    1200,
    '/images/products/golf-links-cover.webp',
    '{"/images/products/golf-links-cover.webp","/images/products/golf-navy-blue.webp","/images/products/golf-pink.webp","/images/products/golf-teal-green.webp"}'::text[],
    '[{"name":"Navy Blue (One More Swing)","value":"bg-blue-900","variantSku":"OG-OG-GOLF-PO-POL-NAVYBLUE"},{"name":"Pink (One More Swing)","value":"bg-[#FFC0CB]","variantSku":"OG-OG-GOLF-PO-POL-PINK"},{"name":"Teal Green (Trust The Swing)","value":"bg-teal-700","variantSku":"OG-OG-GOLF-PO-POL-TEALGREEN"}]'::jsonb,
    '{"S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    'S–5XL',
    'OFFGRID Links Golf Polo — 4-way stretch with breathable collar construction. Built for 18 holes under the tropical sun.',
    'Performance technical golf polo · S–5XL.',
    'Performance Technical Golf Pique',
    'poly_blend',
    'polo',
    '[{"sku":"OG-OGGOLF-PO-POL-NAVYBLUE","designName":"Navy Blue","isActive":true,"imageUrl":"/images/products/golf-navy-blue.webp"},{"sku":"OG-OGGOLF-PO-POL-PINK","designName":"Pink","isActive":true,"imageUrl":"/images/products/golf-pink.webp"},{"sku":"OG-OGGOLF-PO-POL-TEALGREEN","designName":"Teal Green","isActive":true,"imageUrl":"/images/products/golf-teal-green.webp"}]'::jsonb,
    210,
    null,
    'Golf',
    '{"Golf"}'::text[],
    0,
    'active'
  ),
  (
    'og-pickleball-club',
    'og-pickleball-club-collection',
    'OG PICKLEBALL — CLUB COLLECTION',
    'Pickleball',
    '{"Pickleball"}'::text[],
    '{"pickleball"}'::text[],
    850,
    620,
    '/images/products/pickleball-club-cover.webp',
    '{"/images/products/pickleball-club-cover.webp","/images/products/pickleball-club-cream.webp","/images/products/pickleball-club-green.webp","/images/products/pickleball-club-black.webp","/images/products/pickleball-club-violet.webp","/images/products/pickleball-club-white.webp"}'::text[],
    '[{"name":"Pickleball Cream","value":"bg-offgrid-cream","variantSku":"OG-PICKLE-CLUB-SS-DRF-PICKLEBALLCREAM"},{"name":"Pickleball Green","value":"bg-offgrid-green","variantSku":"OG-PICKLE-CLUB-SS-DRF-PICKLEBALLGREEN"},{"name":"Pickleball Black","value":"bg-black","variantSku":"OG-PICKLE-CLUB-SS-DRF-PICKLEBALLBLACK"},{"name":"Pickleball Violet","value":"bg-purple-700","variantSku":"OG-PICKLE-CLUB-SS-DRF-PICKLEBALLVIOLET"},{"name":"Pickleball White","value":"bg-white","variantSku":"OG-PICKLE-CLUB-SS-DRF-PICKLEBALLWHITE"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL"}'::text[],
    '2XS–2XL',
    'Club cut in the OFFGRID pickleball collection. Clean team look for league nights and open play with 27% launch discount.',
    'Pickleball club performance tee (27% OFF).',
    'Performance Dryfit',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-PICKLECLUB-SS-DRF-PICKLEBALLCREAM","designName":"Pickleball Cream","isActive":true,"imageUrl":"/images/products/pickleball-club-cream.webp"},{"sku":"OG-PICKLECLUB-SS-DRF-PICKLEBALLGREEN","designName":"Pickleball Green","isActive":true,"imageUrl":"/images/products/pickleball-club-green.webp"},{"sku":"OG-PICKLECLUB-SS-DRF-PICKLEBALLBLACK","designName":"Pickleball Black","isActive":true,"imageUrl":"/images/products/pickleball-club-black.webp"},{"sku":"OG-PICKLECLUB-SS-DRF-PICKLEBALLVIOLET","designName":"Pickleball Violet","isActive":true,"imageUrl":"/images/products/pickleball-club-violet.webp"},{"sku":"OG-PICKLECLUB-SS-DRF-PICKLEBALLWHITE","designName":"Pickleball White","isActive":true,"imageUrl":"/images/products/pickleball-club-white.webp"}]'::jsonb,
    280,
    null,
    'Sale',
    '{"Sale","Pickleball"}'::text[],
    0,
    'active'
  ),
  (
    'og-pickleball-graphics',
    'og-pickleball-graphic-collection',
    'OG PICKLEBALL — GRAPHIC COLLECTION',
    'Pickleball',
    '{"Pickleball"}'::text[],
    '{"pickleball"}'::text[],
    850,
    850,
    '/images/products/pickleball-alt-cover.webp',
    '{"/images/products/pickleball-alt-cover.webp","/images/products/pickleball-dink-different.webp","/images/products/pickleball-summer-league.webp","/images/products/pickleball-everyday-pickleday.webp","/images/products/pickleball-get-dink-on.webp","/images/products/pickleball-pocket-print.webp"}'::text[],
    '[{"name":"Dink Different (Black)","value":"bg-black","variantSku":"OG-PICKLE-GRAPHICS-SS-DRF-DINKDIFFERENT"},{"name":"Summer League (Royal Blue)","value":"bg-blue-600","variantSku":"OG-PICKLE-GRAPHICS-SS-DRF-SUMMERLEAGUE"},{"name":"Everyday Pickle Day (Pink)","value":"bg-pink-300","variantSku":"OG-PICKLE-GRAPHICS-SS-DRF-EVERYDAYPICKLEDAY"},{"name":"Get Your Dink On (Teal)","value":"bg-teal-700","variantSku":"OG-PICKLE-GRAPHICS-SS-DRF-GETYOURDINKON"},{"name":"Pocket Print (White)","value":"bg-white","variantSku":"OG-PICKLE-GRAPHICS-SS-DRF-POCKETPRINT"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'OFFGRID Pickleball Graphic Collection — signature court graphics including Dink Different, Summer League, Everyday Pickle Day, Get Your Dink On, and Pocket Print with premium front and back court prints.',
    'Signature pickleball graphic tees with front & back court prints.',
    'Drifit Performance Mesh',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-PICKLEGRAPHICS-SS-DRF-DINKDIFFERENT","designName":"Dink Different","isActive":true,"imageUrl":"/images/products/pickleball-dink-different.webp"},{"sku":"OG-PICKLEGRAPHICS-SS-DRF-SUMMERLEAGUE","designName":"Summer League","isActive":true,"imageUrl":"/images/products/pickleball-summer-league.webp"},{"sku":"OG-PICKLEGRAPHICS-SS-DRF-EVERYDAYPICKLEDAY","designName":"Everyday Pickle Day","isActive":true,"imageUrl":"/images/products/pickleball-everyday-pickleday.webp"},{"sku":"OG-PICKLEGRAPHICS-SS-DRF-GETYOURDINKON","designName":"Get Your Dink On","isActive":true,"imageUrl":"/images/products/pickleball-get-dink-on.webp"},{"sku":"OG-PICKLEGRAPHICS-SS-DRF-POCKETPRINT","designName":"Pocket Print","isActive":true,"imageUrl":"/images/products/pickleball-pocket-print.webp"}]'::jsonb,
    310,
    null,
    'Pickleball',
    '{"Pickleball"}'::text[],
    0,
    'active'
  ),
  (
    'salmon-smasher',
    'salmon-smasher',
    'SALMON SMASHER PERFORMANCE',
    'Pickleball',
    '{"Pickleball"}'::text[],
    '{"pickleball"}'::text[],
    900,
    900,
    '/images/products/pickleball-salmon-smasher-ss.webp',
    '{"/images/products/pickleball-salmon-smasher-ss.webp","/images/products/pickleball-salmon-smasher-ls.webp"}'::text[],
    '[{"name":"Short Sleeve (Salmon Pink)","value":"bg-[#FA8072]","variantSku":"OG-SALMON-SMASHER-SS-DRF-SHORTSLEEVE"},{"name":"Long Sleeve (Salmon Pink)","value":"bg-[#E06F62]","variantSku":"OG-SALMON-SMASHER-LS-DRF-LONGSLEEVE"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'Smash like a salmon — vibrant tournament drifit activewear available in both short sleeve and long sleeve cuts.',
    'Salmon smasher performance drifit tee (Short & Long Sleeve).',
    'Performance Drifit',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-SALMONSMASHER-SS-DRF-SHORTSLEEVE","designName":"Short Sleeve","isActive":true,"imageUrl":"/images/products/pickleball-salmon-smasher-ss.webp"},{"sku":"OG-SALMONSMASHER-LS-DRF-LONGSLEEVE","designName":"Long Sleeve","isActive":true,"imageUrl":"/images/products/pickleball-salmon-smasher-ls.webp"}]'::jsonb,
    105,
    null,
    'Pickleball',
    '{"Pickleball"}'::text[],
    0,
    'active'
  )
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  sports = EXCLUDED.sports,
  collection_ids = EXCLUDED.collection_ids,
  base_price = EXCLUDED.base_price,
  price = EXCLUDED.price,
  image = EXCLUDED.image,
  gallery = EXCLUDED.gallery,
  colors = EXCLUDED.colors,
  sizes = EXCLUDED.sizes,
  size_range = EXCLUDED.size_range,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  material = EXCLUDED.material,
  fabric_type = EXCLUDED.fabric_type,
  cut = EXCLUDED.cut,
  variants = EXCLUDED.variants,
  sold = EXCLUDED.sold,
  stock = EXCLUDED.stock,
  tag = EXCLUDED.tag,
  tags = EXCLUDED.tags,
  home_best_seller_rank = EXCLUDED.home_best_seller_rank,
  status = EXCLUDED.status,
  updated_at = now();
