-- Migration: Add complete 29-product catalog across all collections
-- Timestamp: 2026-10-01
-- Idempotent upsert ensuring production checkout and hydration match catalog

INSERT INTO public.og_products (
  id, slug, name, category, sports, collection_ids, base_price, price, image, gallery,
  colors, sizes, size_range, description, short_description, material, fabric_type,
  cut, variants, sold, stock, tag, tags, home_best_seller_rank, status
)
VALUES
  (
    'og-voyager',
    'og-voyager',
    'OG VOYAGER',
    'Ultimate Frisbee',
    '{"Ultimate Frisbee"}'::text[],
    '{"discfest"}'::text[],
    1300,
    1100,
    '/images/community/community-ultimate-skyball.jpg',
    '{}'::text[],
    '[{"name":"Field Black","value":"bg-offgrid-dark"},{"name":"OFFGRID Lime","value":"bg-offgrid-lime"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'OG VOYAGER — OFFGRID ultimate frisbee retail from the Discfest line. Performance drifit for ultimate and disc days. Full sublimation teamwear.',
    'Discfest ultimate frisbee tee · OG VOYAGER.',
    'Premium Drifit',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-OGVOYAGER-SS-DRF-FIELDBLACK","designName":"Field Black","isActive":true},{"sku":"OG-OGVOYAGER-SS-DRF-OFFGRIDLIME","designName":"OFFGRID Lime","isActive":true}]'::jsonb,
    520,
    null,
    'Best Seller',
    '{"Best Seller"}'::text[],
    1,
    'active'
  ),
  (
    'og-stats',
    'og-stats',
    'OG STATS',
    'Ultimate Frisbee',
    '{"Ultimate Frisbee"}'::text[],
    '{"discfest"}'::text[],
    1100,
    1100,
    '/images/community/community-ultimate-catch.jpg',
    '{}'::text[],
    '[{"name":"Field Black","value":"bg-offgrid-dark"},{"name":"OFFGRID Lime","value":"bg-offgrid-lime"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'OG STATS — OFFGRID ultimate frisbee retail from the Discfest line. Performance drifit for ultimate and disc days. Full sublimation teamwear.',
    'Discfest ultimate frisbee tee · OG STATS.',
    'Premium Drifit',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-OGSTATS-SS-DRF-FIELDBLACK","designName":"Field Black","isActive":true},{"sku":"OG-OGSTATS-SS-DRF-OFFGRIDLIME","designName":"OFFGRID Lime","isActive":true}]'::jsonb,
    410,
    null,
    null,
    '{}'::text[],
    2,
    'active'
  ),
  (
    'og-arcade',
    'og-arcade',
    'OG ARCADE',
    'Ultimate Frisbee',
    '{"Ultimate Frisbee"}'::text[],
    '{"discfest"}'::text[],
    1100,
    1100,
    '/images/community/community-ultimate-field.jpg',
    '{}'::text[],
    '[{"name":"Field Black","value":"bg-offgrid-dark"},{"name":"OFFGRID Lime","value":"bg-offgrid-lime"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'OG ARCADE — OFFGRID ultimate frisbee retail from the Discfest line. Performance drifit for ultimate and disc days. Full sublimation teamwear.',
    'Discfest ultimate frisbee tee · OG ARCADE.',
    'Premium Drifit',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-OGARCADE-SS-DRF-FIELDBLACK","designName":"Field Black","isActive":true},{"sku":"OG-OGARCADE-SS-DRF-OFFGRIDLIME","designName":"OFFGRID Lime","isActive":true}]'::jsonb,
    380,
    null,
    null,
    '{}'::text[],
    3,
    'active'
  ),
  (
    'og-comet',
    'og-comet',
    'OG COMET',
    'Ultimate Frisbee',
    '{"Ultimate Frisbee"}'::text[],
    '{"discfest"}'::text[],
    1100,
    1100,
    '/images/community/community-ultimate-skyball.jpg',
    '{}'::text[],
    '[{"name":"Field Black","value":"bg-offgrid-dark"},{"name":"OFFGRID Lime","value":"bg-offgrid-lime"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'OG COMET — OFFGRID ultimate frisbee retail from the Discfest line. Performance drifit for ultimate and disc days. Full sublimation teamwear.',
    'Discfest ultimate frisbee tee · OG COMET.',
    'Premium Drifit',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-OGCOMET-SS-DRF-FIELDBLACK","designName":"Field Black","isActive":true},{"sku":"OG-OGCOMET-SS-DRF-OFFGRIDLIME","designName":"OFFGRID Lime","isActive":true}]'::jsonb,
    295,
    null,
    null,
    '{}'::text[],
    4,
    'active'
  ),
  (
    'og-discfest-towel',
    'og-discfest-towel',
    'OG DISCFEST TOWEL',
    'Ultimate Frisbee',
    '{"Ultimate Frisbee"}'::text[],
    '{"discfest"}'::text[],
    650,
    650,
    '/images/community/product-towel-bench.jpg',
    '{}'::text[],
    '[{"name":"Field Cream","value":"bg-offgrid-cream"}]'::jsonb,
    '{"S","M","L","XL"}'::text[],
    'One size / S–XL pack',
    'OFFGRID Discfest towel — sideline essential for ultimate frisbee game days. Part of our top-selling ultimate frisbee retail line.',
    'Discfest ultimate frisbee towel.',
    'Absorbent cotton terry',
    'cotton',
    'shorts',
    '[]'::jsonb,
    260,
    null,
    'Discfest',
    '{"Discfest"}'::text[],
    0,
    'active'
  ),
  (
    'pilipinas-aouc-jersey',
    'pilipinas-aouc-jersey-2025',
    'PILIPINAS AOUC JERSEY 2025',
    'Pilipinas Collection',
    '{"Ultimate Frisbee"}'::text[],
    '{"pilipinas","discfest"}'::text[],
    1000,
    1000,
    '/images/products/pilipinas-aouc-capiz.webp',
    '{"/images/products/pilipinas-aouc-capiz.webp","/images/products/pilipinas-aouc-lilim.webp","/images/products/pilipinas-aouc-piloncitos.webp"}'::text[],
    '[{"name":"Capiz","value":"bg-[#E6DEC8]"},{"name":"Lilim","value":"bg-[#1E293B]"},{"name":"Piloncitos","value":"bg-[#D97706]"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'Official Pilipinas AOUC 2025 National Team Jersey. Full sublimation dryfit activewear engineered for international ultimate tournament play.',
    'Pilipinas AOUC 2025 National Team Jersey · 2XS–5XL.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-PILIPINASAOUC-SS-DRF-CAPIZ","designName":"Capiz","isActive":true},{"sku":"OG-PILIPINASAOUC-SS-DRF-LILIM","designName":"Lilim","isActive":true},{"sku":"OG-PILIPINASAOUC-SS-DRF-PILONCITOS","designName":"Piloncitos","isActive":true}]'::jsonb,
    145,
    null,
    'Pilipinas',
    '{"Pilipinas","National Team"}'::text[],
    0,
    'active'
  ),
  (
    'pilipinas-ultimate-jersey',
    'pilipinas-ultimate-jersey',
    'PILIPINAS ULTIMATE TEAM JERSEY',
    'Pilipinas Collection',
    '{"Ultimate Frisbee"}'::text[],
    '{"pilipinas"}'::text[],
    1100,
    1100,
    '/images/products/pilipinas-ultimate-blue.webp',
    '{"/images/products/pilipinas-ultimate-blue.webp","/images/products/pilipinas-ultimate-white.webp"}'::text[],
    '[{"name":"National Blue","value":"bg-blue-700"},{"name":"National White","value":"bg-white"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'Pilipinas Ultimate Team Jersey featuring national heraldry and high-breathability performance mesh.',
    'Pilipinas Ultimate Jersey in Blue & White.',
    'Dryfit Polyester',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-PILIPINASULTIMATE-SS-DRF-NATIONALBLUE","designName":"National Blue","isActive":true},{"sku":"OG-PILIPINASULTIMATE-SS-DRF-NATIONALWHITE","designName":"National White","isActive":true}]'::jsonb,
    88,
    null,
    'Pilipinas',
    '{"Pilipinas"}'::text[],
    0,
    'active'
  ),
  (
    'og-padayon-jersey',
    'og-padayon-jersey',
    'PADAYON PILIPINAS JERSEY',
    'Pilipinas Collection',
    '{"Ultimate Frisbee"}'::text[],
    '{"pilipinas"}'::text[],
    1200,
    1200,
    '/images/products/pilipinas-padayon-jersey.webp',
    '{}'::text[],
    '[{"name":"Pilipinas Gold & Sun","value":"bg-[#FFD700]"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL"}'::text[],
    '2XS–4XL',
    'Padayon Pilipinas sleeveless jersey with Baybayin script accents, Philippine Sun details, and customizable back player number.',
    'Padayon sleeveless national jersey with customizable number.',
    'Full Sublimation Dryfit (Customizable number)',
    'dri_fit',
    'tank',
    '[{"sku":"OG-PADAYON-TK-DRF-GOLDSUN","designName":"Gold Sun","isActive":true}]'::jsonb,
    112,
    null,
    'Pilipinas',
    '{"Pilipinas"}'::text[],
    0,
    'active'
  ),
  (
    'running-line',
    'running-performance-line',
    'RUNNING PERFORMANCE LINE 2.0',
    'Running',
    '{"Running"}'::text[],
    '{"running"}'::text[],
    900,
    900,
    '/images/products/running-performance-cover.webp',
    '{"/images/products/running-classic-black.webp","/images/products/running-flow-state-blue.webp","/images/products/running-purpose-green.webp","/images/products/running-catch-me-cream.webp","/images/products/running-stride-club-gray.webp"}'::text[],
    '[{"name":"OFFGRID Classic (Black)","value":"bg-offgrid-dark"},{"name":"The Flow State (Blue)","value":"bg-blue-600"},{"name":"Run With Purpose (Green)","value":"bg-offgrid-green"},{"name":"Catch Me If You Can (Cream)","value":"bg-offgrid-cream"},{"name":"The Stride Club (Dark Gray)","value":"bg-gray-700"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'Running Performance Line 2.0 — built for daily miles and tempo runs with featherweight moisture-wicking comfort.',
    'Running performance graphic tees.',
    'Running Mesh / Drifit',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-RUNNINGLINE-SS-DRF-OFFGRIDCLASSICBLACK","designName":"OFFGRID Classic Black","isActive":true},{"sku":"OG-RUNNINGLINE-SS-DRF-THEFLOWSTATEBLUE","designName":"The Flow State Blue","isActive":true},{"sku":"OG-RUNNINGLINE-SS-DRF-RUNWITHPURPOSEGREEN","designName":"Run With Purpose Green","isActive":true},{"sku":"OG-RUNNINGLINE-SS-DRF-CATCHMEIFYOUCANCREAM","designName":"Catch Me If You Can Cream","isActive":true},{"sku":"OG-RUNNINGLINE-SS-DRF-THESTRIDECLUBDARKGRAY","designName":"The Stride Club Dark Gray","isActive":true}]'::jsonb,
    320,
    null,
    'Running',
    '{"Running"}'::text[],
    0,
    'active'
  ),
  (
    'og-stride-running',
    'og-stride-collection',
    'OFF GRID STRIDE COLLECTION',
    'Running',
    '{"Running"}'::text[],
    '{"running"}'::text[],
    1000,
    1000,
    '/images/products/stride-running-banner.webp',
    '{"/images/products/stride-running-promo.webp","/images/products/stride-running-grid.webp","/images/products/stride-running-detail.webp"}'::text[],
    '[{"name":"White-Teal","value":"bg-teal-400"},{"name":"White-Pink","value":"bg-pink-400"},{"name":"White-Neon Green","value":"bg-lime-400"},{"name":"White-Orange","value":"bg-orange-400"},{"name":"Black-Teal","value":"bg-teal-700"},{"name":"Black-Pink","value":"bg-pink-700"},{"name":"Black-Neon Green","value":"bg-lime-600"},{"name":"Pink-Teal","value":"bg-fuchsia-600"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'Off Grid Stride Collection — high-visibility dual-tone colorways engineered for chasing PRs from morning intervals to night runs.',
    'Chasing PR dual-tone running shirts.',
    'Breathable Running Poly',
    'running_mesh',
    'short_sleeve',
    '[{"sku":"OG-STRIDE-SS-RUN-WHITETEAL","designName":"White-Teal","isActive":true},{"sku":"OG-STRIDE-SS-RUN-WHITEPINK","designName":"White-Pink","isActive":true},{"sku":"OG-STRIDE-SS-RUN-WHITENEONGREEN","designName":"White-Neon Green","isActive":true},{"sku":"OG-STRIDE-SS-RUN-WHITEORANGE","designName":"White-Orange","isActive":true},{"sku":"OG-STRIDE-SS-RUN-BLACKTEAL","designName":"Black-Teal","isActive":true},{"sku":"OG-STRIDE-SS-RUN-BLACKPINK","designName":"Black-Pink","isActive":true},{"sku":"OG-STRIDE-SS-RUN-BLACKNEONGREEN","designName":"Black-Neon Green","isActive":true},{"sku":"OG-STRIDE-SS-RUN-PINKTEAL","designName":"Pink-Teal","isActive":true}]'::jsonb,
    195,
    null,
    'Running',
    '{"Running"}'::text[],
    0,
    'active'
  ),
  (
    'og-motoline',
    'motoline',
    'OFF GRID LIFESTYLE — MOTOLINE',
    'Lifestyle / Motoline',
    '{"Lifestyle"}'::text[],
    '{"lifestyle","running"}'::text[],
    650,
    650,
    '/images/products/motoline-cover.webp',
    '{"/images/products/motoline-full-throttle.webp","/images/products/motoline-takbong-og.webp","/images/products/motoline-stay-offgrid.webp","/images/products/motoline-takbong-pogi.webp"}'::text[],
    '[{"name":"FULL THROTTLE LIFE","value":"bg-offgrid-dark"},{"name":"TAKBONG OG","value":"bg-offgrid-green"},{"name":"STAY OFFGRID","value":"bg-offgrid-lime"},{"name":"TAKBONG POGI MODE","value":"bg-offgrid-cream"}]'::jsonb,
    '{"XS","S","M","L","XL","2XL","3XL","4XL"}'::text[],
    'XS–4XL',
    'MOTOLINE long-sleeve lifestyle & moto kit — gritty street and road runs with iconic Filipino rider catchphrases in OFFGRID colorways.',
    'Long sleeve drifit lifestyle moto gear.',
    'Premium Drifit',
    'dri_fit',
    'long_sleeve',
    '[{"sku":"OG-MOTOLINE-LS-DRF-FULLTHROTTLELIFE","designName":"FULL THROTTLE LIFE","isActive":true},{"sku":"OG-MOTOLINE-LS-DRF-TAKBONGOG","designName":"TAKBONG OG","isActive":true},{"sku":"OG-MOTOLINE-LS-DRF-STAYOFFGRID","designName":"STAY OFFGRID","isActive":true},{"sku":"OG-MOTOLINE-LS-DRF-TAKBONGPOGIMODE","designName":"TAKBONG POGI MODE","isActive":true}]'::jsonb,
    154,
    null,
    'Lifestyle',
    '{"Lifestyle"}'::text[],
    0,
    'active'
  ),
  (
    'the-og-vibe-collection',
    'the-og-vibe-collection',
    'THE OG VIBE STREETWEAR TEE',
    'Lifestyle / OG Vibe',
    '{"Lifestyle"}'::text[],
    '{"lifestyle"}'::text[],
    850,
    850,
    '/images/products/og-vibe-steampunk-black.webp',
    '{"/images/products/og-vibe-blossom-black.webp","/images/products/og-vibe-steampunk-cream.webp","/images/products/og-vibe-blossom-cream.webp"}'::text[],
    '[{"name":"Black Steampunk","value":"bg-black"},{"name":"Black Blossom","value":"bg-neutral-900"},{"name":"Cream Steampunk","value":"bg-[#F5F2EB]"},{"name":"Cream Blossom","value":"bg-offgrid-cream"}]'::jsonb,
    '{"S","M","L","XL","2XL"}'::text[],
    'S–2XL',
    'Lifestyle streetwear for everyday athletes. Heavyweight cotton with premium screen-printed OG Steampunk and Blossom graphics.',
    'Heavyweight cotton streetwear tee.',
    'Heavyweight Cotton Streetwear',
    'cotton',
    'short_sleeve',
    '[{"sku":"OG-THEOGVIBECOLLECTION-SS-COT-BLACKSTEAMPUNK","designName":"Black Steampunk","isActive":true},{"sku":"OG-THEOGVIBECOLLECTION-SS-COT-BLACKBLOSSOM","designName":"Black Blossom","isActive":true},{"sku":"OG-THEOGVIBECOLLECTION-SS-COT-CREAMSTEAMPUNK","designName":"Cream Steampunk","isActive":true},{"sku":"OG-THEOGVIBECOLLECTION-SS-COT-CREAMBLOSSOM","designName":"Cream Blossom","isActive":true}]'::jsonb,
    430,
    null,
    'Lifestyle',
    '{"Lifestyle"}'::text[],
    0,
    'active'
  ),
  (
    'og-momentum-caps',
    'og-momentum-caps',
    'OFF GRID MOMENTUM ATHLETIC CAP',
    'Lifestyle',
    '{"Lifestyle"}'::text[],
    '{"lifestyle"}'::text[],
    950,
    950,
    '/images/products/momentum-cap-cover.webp',
    '{"/images/products/momentum-cap-dark-blue.webp","/images/products/momentum-cap-black.webp","/images/products/momentum-cap-white.webp","/images/products/momentum-cap-sky-blue.webp","/images/products/momentum-cap-pink.webp"}'::text[],
    '[{"name":"Dark Blue","value":"bg-blue-900"},{"name":"Black","value":"bg-black"},{"name":"White","value":"bg-white"},{"name":"Sky Blue","value":"bg-sky-400"},{"name":"Pink","value":"bg-pink-400"}]'::jsonb,
    '{"One Size"}'::text[],
    'One Size (Adjustable strap)',
    'Off Grid Lifestyle Momentum Caps — structured crown with moisture-managing sweatband and adjustable fit for sun protection and style.',
    'Breathable athletic cap with adjustable strap.',
    'Structured Breathable Twill',
    'poly_blend',
    'cap',
    '[{"sku":"OG-MOMENTUMCAPS-CP-PLY-DARKBLUE","designName":"Dark Blue","isActive":true},{"sku":"OG-MOMENTUMCAPS-CP-PLY-BLACK","designName":"Black","isActive":true},{"sku":"OG-MOMENTUMCAPS-CP-PLY-WHITE","designName":"White","isActive":true},{"sku":"OG-MOMENTUMCAPS-CP-PLY-SKYBLUE","designName":"Sky Blue","isActive":true},{"sku":"OG-MOMENTUMCAPS-CP-PLY-PINK","designName":"Pink","isActive":true}]'::jsonb,
    70,
    null,
    'Headwear',
    '{"Headwear"}'::text[],
    0,
    'active'
  ),
  (
    'og-microfiber-towel',
    'og-microfiber-towel',
    'OFF GRID MICROFIBER PERFORMANCE TOWEL',
    'Lifestyle',
    '{"Lifestyle"}'::text[],
    '{"lifestyle"}'::text[],
    650,
    650,
    '/images/products/towel-microfiber-promo.webp',
    '{"/images/products/towel-microfiber-progress.webp","/images/products/towel-microfiber-hand-spec.webp","/images/products/towel-microfiber-detail.webp","/images/products/towel-microfiber-flatlay.webp"}'::text[],
    '[{"name":"OFFGRID Lime / Field Black","value":"bg-offgrid-green"}]'::jsonb,
    '{"Face (30x30)","Hand (35x75)","Bath (140x70)"}'::text[],
    'Face, Hand, Bath sizes',
    'Ultra-compact quick-drying microfiber performance towel. Dual-texture functionality: smooth high-definition printed face with high-absorption back loop.',
    'Quick-drying printed microfiber sports towel.',
    'Microfiber Blend (Polyester/Polyamide)',
    'poly_blend',
    'shorts',
    '[{"sku":"OG-MICROFIBERTOWEL-AC-MCF-FACE30X30","designName":"Face 30x30","isActive":true},{"sku":"OG-MICROFIBERTOWEL-AC-MCF-HAND35X75","designName":"Hand 35x75","isActive":true},{"sku":"OG-MICROFIBERTOWEL-AC-MCF-BATH140X70","designName":"Bath 140x70","isActive":true}]'::jsonb,
    160,
    null,
    'Lifestyle',
    '{"Lifestyle"}'::text[],
    0,
    'active'
  ),
  (
    'og-primal-sleeveless',
    'og-primal-sleeveless',
    'OG PRIMAL POWER — SLEEVELESS TANK',
    'Primal Collection',
    '{"Gym & Training"}'::text[],
    '{"primal"}'::text[],
    900,
    900,
    '/images/products/primal-sleeveless-black-green.webp',
    '{"/images/products/primal-sleeveless-blue-ivory.webp","/images/products/primal-sleeveless-green-pink.webp","/images/products/primal-sleeveless-teal-white.webp"}'::text[],
    '[{"name":"Black/Green","value":"bg-black"},{"name":"Blue/Ivory","value":"bg-blue-800"},{"name":"Green/Pink","value":"bg-emerald-700"},{"name":"Teal/White","value":"bg-teal-600"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Primal Power Sleeveless Tank — maximum mobility for heavy lifts and intense conditioning sessions.',
    'Primal power sleeveless gym tank.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'sleeveless',
    '[{"sku":"OG-PRIMALSLEEVELESS-SL-DRF-BLACKGREEN","designName":"Black/Green","isActive":true},{"sku":"OG-PRIMALSLEEVELESS-SL-DRF-BLUEIVORY","designName":"Blue/Ivory","isActive":true},{"sku":"OG-PRIMALSLEEVELESS-SL-DRF-GREENPINK","designName":"Green/Pink","isActive":true},{"sku":"OG-PRIMALSLEEVELESS-SL-DRF-TEALWHITE","designName":"Teal/White","isActive":true}]'::jsonb,
    180,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-primal-shortsleeve',
    'og-primal-shortsleeve',
    'OG PRIMAL POWER — SHORT SLEEVE',
    'Primal Collection',
    '{"Gym & Training"}'::text[],
    '{"primal"}'::text[],
    900,
    900,
    '/images/products/primal-shortsleeve-black-green.webp',
    '{"/images/products/primal-shortsleeve-blue-ivory.webp","/images/products/primal-shortsleeve-green-pink.webp","/images/products/primal-shortsleeve-teal-white.webp"}'::text[],
    '[{"name":"Black/Green","value":"bg-black"},{"name":"Blue/Ivory","value":"bg-blue-800"},{"name":"Green/Pink","value":"bg-emerald-700"},{"name":"Teal/White","value":"bg-teal-600"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Primal Power Short Sleeve Tee — high-density sublimated gym gear tailored for training and physique.',
    'Primal power short sleeve performance shirt.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-PRIMALSHORTSLEEVE-SS-DRF-BLACKGREEN","designName":"Black/Green","isActive":true},{"sku":"OG-PRIMALSHORTSLEEVE-SS-DRF-BLUEIVORY","designName":"Blue/Ivory","isActive":true},{"sku":"OG-PRIMALSHORTSLEEVE-SS-DRF-GREENPINK","designName":"Green/Pink","isActive":true},{"sku":"OG-PRIMALSHORTSLEEVE-SS-DRF-TEALWHITE","designName":"Teal/White","isActive":true}]'::jsonb,
    240,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-primal-longsleeve',
    'og-primal-longsleeve',
    'OG PRIMAL POWER — LONG SLEEVE',
    'Primal Collection',
    '{"Gym & Training"}'::text[],
    '{"primal"}'::text[],
    1100,
    1100,
    '/images/products/primal-longsleeve-black-green.webp',
    '{"/images/products/primal-longsleeve-blue-ivory.webp","/images/products/primal-longsleeve-green-pink.webp","/images/products/primal-longsleeve-teal-white.webp"}'::text[],
    '[{"name":"Black/Green","value":"bg-black"},{"name":"Blue/Ivory","value":"bg-blue-800"},{"name":"Green/Pink","value":"bg-emerald-700"},{"name":"Teal/White","value":"bg-teal-600"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Primal Power Long Sleeve — athletic taper with full arm coverage for warmup, outdoors, and strength training.',
    'Primal power long sleeve performance shirt.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'long_sleeve',
    '[{"sku":"OG-PRIMALLONGSLEEVE-LS-DRF-BLACKGREEN","designName":"Black/Green","isActive":true},{"sku":"OG-PRIMALLONGSLEEVE-LS-DRF-BLUEIVORY","designName":"Blue/Ivory","isActive":true},{"sku":"OG-PRIMALLONGSLEEVE-LS-DRF-GREENPINK","designName":"Green/Pink","isActive":true},{"sku":"OG-PRIMALLONGSLEEVE-LS-DRF-TEALWHITE","designName":"Teal/White","isActive":true}]'::jsonb,
    130,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-primal-hoodie',
    'og-primal-hoodie',
    'OG PRIMAL POWER — HOODIE',
    'Primal Collection',
    '{"Gym & Training"}'::text[],
    '{"primal"}'::text[],
    1100,
    1100,
    '/images/products/primal-hoodie-black-green.webp',
    '{"/images/products/primal-hoodie-blue-ivory.webp","/images/products/primal-hoodie-green-pink.webp","/images/products/primal-hoodie-teal-white.webp"}'::text[],
    '[{"name":"Black/Green","value":"bg-black"},{"name":"Blue/Ivory","value":"bg-blue-800"},{"name":"Green/Pink","value":"bg-emerald-700"},{"name":"Teal/White","value":"bg-teal-600"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Primal Power Performance Hoodie — lightweight workout layer with drawstring hood and athletic cut.',
    'Primal power performance hoodie.',
    'Performance Sublimated Poly Hoodie',
    'dri_fit',
    'hoodie',
    '[{"sku":"OG-PRIMALHOODIE-HD-DRF-BLACKGREEN","designName":"Black/Green","isActive":true},{"sku":"OG-PRIMALHOODIE-HD-DRF-BLUEIVORY","designName":"Blue/Ivory","isActive":true},{"sku":"OG-PRIMALHOODIE-HD-DRF-GREENPINK","designName":"Green/Pink","isActive":true},{"sku":"OG-PRIMALHOODIE-HD-DRF-TEALWHITE","designName":"Teal/White","isActive":true}]'::jsonb,
    95,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-solar-sleeveless',
    'og-solar-sleeveless',
    'OG SOLAR RISE — SLEEVELESS TANK',
    'Solar Collection',
    '{"Gym & Training"}'::text[],
    '{"solar"}'::text[],
    900,
    900,
    '/images/products/solar-sleeveless-white-teal.webp',
    '{"/images/products/solar-sleeveless-white-red.webp","/images/products/solar-sleeveless-blue-yellow.webp","/images/products/solar-sleeveless-black-teal.webp","/images/products/solar-sleeveless-black-yellow.webp"}'::text[],
    '[{"name":"White/Teal","value":"bg-teal-400"},{"name":"White/Red","value":"bg-red-500"},{"name":"Blue/Yellow","value":"bg-yellow-400"},{"name":"Black/Teal","value":"bg-teal-700"},{"name":"Black/Yellow","value":"bg-neutral-900"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Solar Rise Sleeveless Tank — energized graphics and lightweight ventilation for heavy training sessions.',
    'Solar Rise sleeveless athletic tank.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'sleeveless',
    '[{"sku":"OG-SOLARSLEEVELESS-SL-DRF-WHITETEAL","designName":"White/Teal","isActive":true},{"sku":"OG-SOLARSLEEVELESS-SL-DRF-WHITERED","designName":"White/Red","isActive":true},{"sku":"OG-SOLARSLEEVELESS-SL-DRF-BLUEYELLOW","designName":"Blue/Yellow","isActive":true},{"sku":"OG-SOLARSLEEVELESS-SL-DRF-BLACKTEAL","designName":"Black/Teal","isActive":true},{"sku":"OG-SOLARSLEEVELESS-SL-DRF-BLACKYELLOW","designName":"Black/Yellow","isActive":true}]'::jsonb,
    110,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-solar-shortsleeve',
    'og-solar-shortsleeve',
    'OG SOLAR RISE — SHORT SLEEVE',
    'Solar Collection',
    '{"Gym & Training"}'::text[],
    '{"solar"}'::text[],
    1000,
    1000,
    '/images/products/solar-shortsleeve-white-teal.webp',
    '{"/images/products/solar-shortsleeve-white-red.webp","/images/products/solar-shortsleeve-blue-yellow.webp"}'::text[],
    '[{"name":"White/Teal","value":"bg-teal-400"},{"name":"White/Red","value":"bg-red-500"},{"name":"Blue/Yellow","value":"bg-yellow-400"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Solar Rise Short Sleeve — radiant gradient motifs on sweat-wicking dryfit fabric.',
    'Solar Rise short sleeve performance tee.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-SOLARSHORTSLEEVE-SS-DRF-WHITETEAL","designName":"White/Teal","isActive":true},{"sku":"OG-SOLARSHORTSLEEVE-SS-DRF-WHITERED","designName":"White/Red","isActive":true},{"sku":"OG-SOLARSHORTSLEEVE-SS-DRF-BLUEYELLOW","designName":"Blue/Yellow","isActive":true}]'::jsonb,
    140,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-solar-longsleeve',
    'og-solar-longsleeve',
    'OG SOLAR RISE — LONG SLEEVE',
    'Solar Collection',
    '{"Gym & Training"}'::text[],
    '{"solar"}'::text[],
    1100,
    1100,
    '/images/products/solar-longsleeve-white-teal.webp',
    '{"/images/products/solar-longsleeve-white-red.webp","/images/products/solar-longsleeve-blue-yellow.webp"}'::text[],
    '[{"name":"White/Teal","value":"bg-teal-400"},{"name":"White/Red","value":"bg-red-500"},{"name":"Blue/Yellow","value":"bg-yellow-400"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    '2XS–5XL',
    'OG Solar Rise Long Sleeve — solar flare graphics with full coverage against the sun and elements.',
    'Solar Rise long sleeve performance shirt.',
    'Dryfit Polyester, Full Sublimation',
    'dri_fit',
    'long_sleeve',
    '[{"sku":"OG-SOLARLONGSLEEVE-LS-DRF-WHITETEAL","designName":"White/Teal","isActive":true},{"sku":"OG-SOLARLONGSLEEVE-LS-DRF-WHITERED","designName":"White/Red","isActive":true},{"sku":"OG-SOLARLONGSLEEVE-LS-DRF-BLUEYELLOW","designName":"Blue/Yellow","isActive":true}]'::jsonb,
    90,
    null,
    'Gym & Training',
    '{"Gym & Training"}'::text[],
    0,
    'active'
  ),
  (
    'og-golf',
    'og-links-golf-polo',
    'OFF GRID LIFESTYLE — LINKS GOLF POLO',
    'Golf',
    '{"Golf"}'::text[],
    '{"golf"}'::text[],
    1200,
    1200,
    '/images/products/golf-links-cover.webp',
    '{"/images/products/golf-navy-blue.webp","/images/products/golf-pink.webp","/images/products/golf-teal-green.webp"}'::text[],
    '[{"name":"Navy Blue (One More Swing)","value":"bg-blue-900"},{"name":"Pink (One More Swing)","value":"bg-[#FFC0CB]"},{"name":"Teal Green (Trust The Swing)","value":"bg-teal-700"}]'::jsonb,
    '{"S","M","L","XL","2XL","3XL","4XL","5XL"}'::text[],
    'S–5XL',
    'OFFGRID Links Golf Polo — 4-way stretch with breathable collar construction. Built for 18 holes under the tropical sun.',
    'Performance technical golf polo · S–5XL.',
    'Performance Technical Golf Pique',
    'poly_blend',
    'polo',
    '[{"sku":"OG-OGGOLF-PO-POL-NAVYBLUE","designName":"Navy Blue","isActive":true},{"sku":"OG-OGGOLF-PO-POL-PINK","designName":"Pink","isActive":true},{"sku":"OG-OGGOLF-PO-POL-TEALGREEN","designName":"Teal Green","isActive":true}]'::jsonb,
    210,
    null,
    'Golf',
    '{"Golf"}'::text[],
    0,
    'active'
  ),
  (
    'og-pickleball',
    'og-pickleball',
    'OG PICKLEBALL CLASSIC',
    'Pickleball',
    '{"Pickleball"}'::text[],
    '{"pickleball"}'::text[],
    900,
    900,
    '/images/products/pickleball-lifestyle-shirt.webp',
    '{}'::text[],
    '[{"name":"Green","value":"bg-offgrid-green"},{"name":"Blue","value":"bg-blue-600"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'Core OFFGRID pickleball tee. Soft combed cotton for open play and sideline hangs.',
    'Core pickleball cotton tee.',
    'Soft Combed Cotton',
    'cotton',
    'short_sleeve',
    '[{"sku":"OG-OGPICKLEBALL-SS-COT-GREEN","designName":"Green","isActive":true},{"sku":"OG-OGPICKLEBALL-SS-COT-BLUE","designName":"Blue","isActive":true}]'::jsonb,
    342,
    null,
    'Pickleball',
    '{"Pickleball"}'::text[],
    0,
    'active'
  ),
  (
    'og-pickleball-club',
    'og-pickleball-club-collection',
    'OG PICKLEBALL — CLUB COLLECTION',
    'Pickleball',
    '{"Pickleball"}'::text[],
    '{"pickleball"}'::text[],
    850,
    620,
    '/images/products/pickleball-club-cover.webp',
    '{"/images/products/pickleball-club-black.webp","/images/products/pickleball-club-cream.webp","/images/products/pickleball-club-green.webp","/images/products/pickleball-club-violet.webp","/images/products/pickleball-club-white.webp"}'::text[],
    '[{"name":"Pickleball Cream","value":"bg-offgrid-cream"},{"name":"Pickleball Green","value":"bg-offgrid-green"},{"name":"Pickleball Black","value":"bg-black"},{"name":"Pickleball Violet","value":"bg-purple-700"},{"name":"Pickleball White","value":"bg-white"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL"}'::text[],
    '2XS–2XL',
    'Club cut in the OFFGRID pickleball collection. Clean team look for league nights and open play with 27% launch discount.',
    'Pickleball club performance tee (27% OFF).',
    'Performance Dryfit',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-PICKLECLUB-SS-DRF-PICKLEBALLCREAM","designName":"Pickleball Cream","isActive":true},{"sku":"OG-PICKLECLUB-SS-DRF-PICKLEBALLGREEN","designName":"Pickleball Green","isActive":true},{"sku":"OG-PICKLECLUB-SS-DRF-PICKLEBALLBLACK","designName":"Pickleball Black","isActive":true},{"sku":"OG-PICKLECLUB-SS-DRF-PICKLEBALLVIOLET","designName":"Pickleball Violet","isActive":true},{"sku":"OG-PICKLECLUB-SS-DRF-PICKLEBALLWHITE","designName":"Pickleball White","isActive":true}]'::jsonb,
    280,
    null,
    'Sale',
    '{"Sale","Pickleball"}'::text[],
    0,
    'active'
  ),
  (
    'everyday-is-pickle-day',
    'everyday-is-pickle-day',
    'EVERYDAY IS PICKLE DAY',
    'Pickleball',
    '{"Pickleball"}'::text[],
    '{"pickleball"}'::text[],
    850,
    850,
    '/images/products/pickleball-everyday-pickleday.webp',
    '{}'::text[],
    '[{"name":"White-Pink","value":"bg-pink-100"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'Everyday is pickle day graphic tee for avid players.',
    'Pickle day casual tee.',
    'Cotton Lifestyle Blend',
    'cotton',
    'short_sleeve',
    '[{"sku":"OG-EVERYDAYPICKLE-SS-COT-WHITEPINK","designName":"White-Pink","isActive":true}]'::jsonb,
    230,
    null,
    'Pickleball',
    '{"Pickleball"}'::text[],
    0,
    'active'
  ),
  (
    'get-your-dink',
    'get-your-dink',
    'GET YOUR DINK ON',
    'Pickleball',
    '{"Pickleball"}'::text[],
    '{"pickleball"}'::text[],
    850,
    850,
    '/images/products/pickleball-get-dink-on.webp',
    '{}'::text[],
    '[{"name":"Green","value":"bg-offgrid-green"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'Get your dink on — court-ready casual tee.',
    'Get your dink tee.',
    'Soft Cotton Tee',
    'cotton',
    'short_sleeve',
    '[{"sku":"OG-GETDINK-SS-COT-GREEN","designName":"Green","isActive":true}]'::jsonb,
    310,
    null,
    'Pickleball',
    '{"Pickleball"}'::text[],
    0,
    'active'
  ),
  (
    'pickleball-lifestyle',
    'pickleball-lifestyle',
    'OG PICKLEBALL — LIFESTYLE',
    'Pickleball',
    '{"Pickleball"}'::text[],
    '{"pickleball"}'::text[],
    850,
    850,
    '/images/products/pickleball-lifestyle-shirt.webp',
    '{}'::text[],
    '[{"name":"White","value":"bg-white"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'Lifestyle cut in the OFFGRID pickleball line — court-to-street tee in comfortable cotton.',
    'Pickleball lifestyle tee.',
    'Comfort Cotton',
    'cotton',
    'short_sleeve',
    '[{"sku":"OG-PICKLELIFESTYLE-SS-COT-WHITE","designName":"White","isActive":true}]'::jsonb,
    180,
    null,
    'Pickleball',
    '{"Pickleball"}'::text[],
    0,
    'active'
  ),
  (
    'salmon-smasher',
    'salmon-smasher',
    'SALMON SMASHER PERFORMANCE',
    'Pickleball',
    '{"Pickleball"}'::text[],
    '{"pickleball"}'::text[],
    900,
    900,
    '/images/products/pickleball-salmon-smasher-ss.webp',
    '{"/images/products/pickleball-salmon-smasher-ls.webp"}'::text[],
    '[{"name":"Salmon Pink","value":"bg-[#FA8072]"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'Smash like a salmon — vibrant tournament drifit tee.',
    'Salmon smasher performance tee.',
    'Performance Drifit',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-SALMONSMASHER-SS-DRF-SALMONPINK","designName":"Salmon Pink","isActive":true}]'::jsonb,
    105,
    null,
    'Pickleball',
    '{"Pickleball"}'::text[],
    0,
    'active'
  ),
  (
    'og-dink-different',
    'og-dink-different',
    'OG DINK DIFFERENT',
    'Pickleball',
    '{"Pickleball"}'::text[],
    '{"pickleball"}'::text[],
    1100,
    1100,
    '/images/products/pickleball-dink-different.webp',
    '{}'::text[],
    '[{"name":"Black","value":"bg-black"}]'::jsonb,
    '{"2XS","XS","S","M","L","XL","2XL","3XL"}'::text[],
    '2XS–3XL',
    'Dink different. Stand out on the pickleball court.',
    'Dink different performance tee.',
    'Drifit Performance Mesh',
    'dri_fit',
    'short_sleeve',
    '[{"sku":"OG-DINKDIFFERENT-SS-DRF-BLACK","designName":"Black","isActive":true}]'::jsonb,
    215,
    null,
    'Pickleball',
    '{"Pickleball"}'::text[],
    0,
    'active'
  )
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  sports = EXCLUDED.sports,
  collection_ids = EXCLUDED.collection_ids,
  base_price = EXCLUDED.base_price,
  price = EXCLUDED.price,
  image = EXCLUDED.image,
  gallery = EXCLUDED.gallery,
  colors = EXCLUDED.colors,
  sizes = EXCLUDED.sizes,
  size_range = EXCLUDED.size_range,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  material = EXCLUDED.material,
  fabric_type = EXCLUDED.fabric_type,
  cut = EXCLUDED.cut,
  variants = EXCLUDED.variants,
  sold = EXCLUDED.sold,
  stock = EXCLUDED.stock,
  tag = EXCLUDED.tag,
  tags = EXCLUDED.tags,
  home_best_seller_rank = EXCLUDED.home_best_seller_rank,
  status = EXCLUDED.status,
  updated_at = now();
